// Tips
export const tip1 = `When adopting, you are making a commitment to care for an animal for the rest of its life—that could mean 10 to 15 years for dogs and up to 20 years for cats. As you go through lifestyle changes such as moves, the birth of children and new jobs, your animal will remain a permanent part of your life. If circumstances change, will you still be able to care for your pet?`
export const tip2 = `Your personality and lifestyle, along with challenges such as space restrictions and amount of time spent at home, should be explored to determine what pet is right for your household. Research different breeds and ask shelter staffers for guidance—they're experts at making perfect matches!`
export const tip3 = `Whether it's tightly sealing your garbage cans or paying attention to dangerous decorations during the holidays, you'll need to make your home safe before adopting. That includes keeping toxic foods, pet-unfriendly plants and dangerous household items out of paw's reach. Here are some suggestions for preparing your home to welcome a new canine or feline companion`
export const tip3_1 = `Provide your new cat with a variety of scratching posts and perches.`
export const tip3_2 = `Use dog crates and gates to confine your new dog when home alone until his house manners earn him unsupervised freedom.`
export const tip3_3 = `Avoid vertical blinds, pooling drapery, ornate tassels and long cords that can become strangulation hazards.`
export const tip3_4 = `Provide plenty of “legal” things for your dog to chew. If he has attractive toys and bones of its own, your dog will be much less likely to gnaw on your things!`
export const tip3_5 = `Provide your new cat with a variety of scratching posts and perches.`
export const tip4_1 = `If there are young children in your home, a puppy may not be your best bet. You may want to consider adopting a medium-sized dog over five months of age.`
export const tip4_2 = `It is a good idea to draw up a schedule of who in the family will help with the care of your new dog, including walking, playing, feeding and grooming.`
export const tip4_3 = `Don’t forget to have your new friend spayed or neutered. Socialization is the key to a happy and confident dog.`
export const tip5_1 = `Make sure everyone in the house is prepared to have a cat.`
export const tip5_2 = `Cats can be very independent. Make sure everyone knows that the fun begins only after the cat feels safe and her needs are met.`
export const tip5_3 = `Once you're sure everyone is ready for feeding, litter changing and grooming, you can divvy up chores among family members so everyone is prepared to care for kitty before she arrives.`
export const tip5_4 = `As with dogs, it’s important to have your new feline friend spayed or neutered.`

// Benefits
export const benefit1 = `Too often, shelters euthanize animals due to room constraints, but if more people adopted pets instead of buying them, the number of pets euthanized would lower dramatically. 
When you adopt, not only do you save your loving new companion, but you make space for other animals who desperately need it, creating a domino effect of goodness.`
export const benefit2 = `While some shelter animals come in as strays, many end up there because of human problems like a move or divorce, not because the animal wasn’t a good pet. Many are already house-trained and used to living with families, so training comes more naturally.`
export const benefit3 = `When you get a dog from a pet store, the transaction usually ends once you exit the door. Many pet stores don’t have the resources or knowledge to provide any support if you have questions or problems with your new pet. This helps ease the transition, and more often than not, shelters are happy to help you through the introductory period because they care that the animal goes to a happy home.`

// Pet Care
export const feedDog1 = `Puppies eight to 12 weeks old need four meals a day.`
export const feedDog2 = `Feed puppies three to six months old three meals a day`
export const feedDog3 = `Feed puppies six months to one year two meals a day.`
export const feedDog4 = `When your dog reaches his first birthday, one meal a day is usually enough.`
export const feedDog5 = `For some dogs, including larger canines or those prone to bloat, it's better to feed two smaller meals`
export const feedDog6 = `Premium-quality dry food provides a well-balanced diet for adult dogs and may be mixed with water, broth or canned food. Your dog may enjoy cottage cheese, cooked egg or fruits and vegetables, but these additions should not total more than ten percent of his daily food intake.`
export const dogExercise = `Dogs need exercise to burn calories, stimulate their minds, and stay healthy. Individual exercise needs vary based on breed or breed mix, sex, age and level of health. Exercise also tends to help dogs avoid boredom, which can lead to destructive behaviors. Supervised fun and games will satisfy many of your pet's instinctual urges to dig, herd, chew, retrieve and chase.`
export const dogGrooming = `Help keep your dog clean and reduce shedding with frequent brushing. Check for fleas and ticks daily during warm weather. Most dogs don't need to be bathed more than a few times a year. Before bathing, comb or cut out all mats from the coat. Carefully rinse all soap out of the coat, or the dirt will stick to soap residue.`
export const dogMeds = `Never give your dog medication that has not been prescribed by a veterinarian. If you suspect that your animal has ingested a poisonous substance, call your veterinarian`
export const dogNeuter1 = `Female dogs should be spayed and male dogs neutered by six months of age.`
export const dogNeuter2 = `Your female pet will live a longer, healthier life. Spaying helps prevent uterine infections and breast tumors, which are malignant or cancerous in about 50 percent of dogs and 90 percent of cats. Spaying your pet before her first heat offers the best protection from these diseases.`
export const dogNeuter3 = `Neutering your male companion prevents testicular cancer and some prostate problems.`

export const feedCat1 = `We recommend purchasing high-quality, brand-name kitten or cat food. Your veterinarian will be able to assess your new cat or kitten and determine the best diet. Factors such as age, activity level and health make a difference in what and how much a cat should eat`
export const feedCat2 = `Cats require taurine, an essential amino acid, for heart and eye health. The food you choose should be balanced for the life stage of your cat or kitten. Properly balanced foods will contain taurine.`
export const feedCat3 = `You will need to provide fresh, clean water at all times, and wash and refill your cat’s water bowls daily`
export const feedCat4 = `Take your pet to your veterinarian if signs of anorexia, diarrhea, vomiting or lethargy continue for more than two days.`
export const catGrooming = `Most cats stay relatively clean and rarely need a bath, but you should brush or comb your cat regularly. Frequent brushing helps keep your cat's coat clean, reduces the amount of shedding and cuts down on the incidence of hairballs.`
export const catLitter = `All indoor cats need a litter box, which should be placed in a quiet, accessible location. In a multi-level home, one box per floor is recommended. Avoid moving the box unless absolutely necessary, but if you must do so, move the box just a few inches per day. Keep in mind that cats won't use a messy, smelly litter box, so scoop solid wastes out of the box at least once a day. Dump everything, wash with a mild detergent and refill at least once a week; you can do this less frequently if using clumping litter. Don't use ammonia, deodorants or scents, especially lemon, when cleaning the litter box. If your cat will not use a litterbox, please consult with your veterinarian. Sometimes refusal to use a litter box is based on a medical condition that required treatment.`
export const catMeds1 = `Never give your cat medication that has not been prescribed by a veterinarian. If you suspect that your animal has ingested a poisonous substance, call your veterinarian`
export const catMeds2 = `Your cat should see the veterinarian at least once a year for an examination and annual shots, and immediately if she is sick or injured.`
export const catNeuter1 = `Female cats should be spayed and male cats neutered by five months of age.`
export const catNeuter2 = `Your veterinarian will make recommendations based on your cat's age and health.`

// RA 8485
export const section1 = `It is the purpose of this Act to protect and promote the welfare of all animals in the Philippines by supervising and regulating the establishment and operations of all facilities utilized for breeding, maintaining, keeping, treating or training of all animals either as objects of trade or as household pets. For purposes of this Act, pet animal shall include birds.`
export const section2 = `No person, association, partnership, corporation, cooperative or any government agency or instrumentality including slaughter houses shall establish, maintain and operate any pet shop, kennel, veterinary clinic, veterinary hospital, stockyard, corral, stud farm or stock farm or zoo for the breeding, treatment, sale or trading, or training of animals without first securing from the Bureau of Animal Industry a certificate of registration therefor.`
export const section3 = `The Director of the Bureau of Animal Industry shall supervise and regulate the establishment, operation and maintenance of pet shops, kennels, veterinary clinics, veterinary hospitals, stockyards, corrals, stud farms and zoos and any other form or structure for the confinement of animals where they are bred, treated, maintained, or kept either for sale or trade or for training as well as the transport of such animals in any form of public or private transportation facility in order to provide maximum comfort while in transit and minimize, if not totally eradicate, incidence of sickness and death and prevent any cruelty from being inflicted upon the animals.`
export const section4 = `It shall be the duty of any owner or operator of any land, air or water public utility transporting pet, wildlife and all other animals to provide in all cases adequate, clean and sanitary facilities for the safe conveyance and delivery thereof to their consignee at the place of consignment. They shall provide sufficient food and water for such animals while in transit for more than twelve (12) hours or whenever necessary. \n\nNo public utility shall transport any such animal without a written permit from the Director of the Bureau of Animal Industry or his/her authorized representative. \n\nNo cruel confinement or restraint shall be made on such animals while being transported. Any form of cruelty shall be penalized even if the transporter has obtained a permit from the Bureau of Animal Industry. Cruelty in transporting includes overcrowding, placing of animals in the trunks or under the hood trunks of the vehicles.`
export const section5 = `There is hereby created a Committee on Animal Welfare attached to the Department of Agriculture which shall, subject to the approval of the Secretary of the Department of Agriculture, issue the necessary rules and regulations for the strict implementation of the provisions of this Act, including the setting of safety and sanitary standards, within thirty (30) calendar days following its approval. Such guidelines shall be reviewed by the Committee every three (3) years from its implementation or whenever necessary.`
export const section6 = `It shall be unlawful for any person to torture any animal, to neglect to provide adequate care, sustenance or shelter, or maltreat any animal or to subject any dog or horse to dogfights or horsefights, kill or cause or procure to be tortured or deprived of adequate care, sustenance or shelter, or maltreat or use the same in research or experiments not expressly authorized by the Committee on Animal Welfare.`
export const section7 = `It shall be the duty of every person to protect the natural habitat of the wildlife. The destruction of said habitat shall be considered as a form of cruelty to animals and its preservation is a way of protecting the animals.`
export const section8 = `Any person who violates any of the provisions of this Act shall, upon conviction by final judgment, be punished by imprisonment of not less than six (6) months nor more than two (2) years or a fine of not less than One thousand pesos (P1,000.00) nor more than Five thousand pesos (P5,000.00) or both at the discretion of the Court. If the violation is committed by a juridical person, the officer responsible therefor shall serve the imprisonment when imposed. If the violation is committed by an alien, he or she shall be immediately deported after service of sentence without any further proceedings.`
export const section9 = `All laws, acts, decrees, executive orders, rules and regulations inconsistent with the provisions of this Act are hereby repealed or modified accordingly.`
export const section10 = `This Act shall take effect fifteen (15) days after its publication in at least two (2) newspapers of general circulation. \n\nApproved: February 11, 1998`
